CREATE DATABASE mana;
USE mana;

CREATE TABLE Sorteo ( ID_SORTEO INT AUTO_INCREMENT PRIMARY KEY, Premio VARCHAR(255), Cantidad INT, Fecha_realización DATE );
CREATE TABLE Cliente ( ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY, Cédula VARCHAR(20), Nombre VARCHAR(255), Deuda DECIMAL(10, 2) DEFAULT '0', Fecha_de_Nacimiento DATE, Tickets_de_Sorteo INT DEFAULT '0', Contacto VARCHAR(255), RUT VARCHAR(20) DEFAULT 'no tiene',Activo BOOLEAN DEFAULT TRUE );
CREATE TABLE Ganador ( ID_CLIENTE INT, ID_SORTEO INT, FOREIGN KEY (ID_CLIENTE) REFERENCES Cliente(ID_CLIENTE), FOREIGN KEY (ID_SORTEO) REFERENCES Sorteo(ID_SORTEO) );
CREATE TABLE Venta ( ID_VENTA INT AUTO_INCREMENT PRIMARY KEY, Precio_Final DECIMAL(10, 2), Fecha_Venta DATE, ID_CLIENTE INT, FOREIGN KEY (ID_CLIENTE) REFERENCES Cliente(ID_CLIENTE));
CREATE TABLE Cobro ( ID_COBRO INT AUTO_INCREMENT PRIMARY KEY, Monto DECIMAL(10, 2), Fecha_Cobro DATE, ID_CLIENTE INT, ID_VENTA INT, FOREIGN KEY (ID_CLIENTE) REFERENCES Cliente(ID_CLIENTE), FOREIGN KEY (ID_VENTA) REFERENCES Venta(ID_VENTA) );
CREATE TABLE Categoría ( ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY, Título VARCHAR(255), Descripción TEXT);
CREATE TABLE IVA ( ID_IVA INT AUTO_INCREMENT PRIMARY KEY, Tipo VARCHAR(50), Valor DECIMAL(5, 2));
CREATE TABLE Medida ( ID_UNIDAD INT AUTO_INCREMENT PRIMARY KEY, Unidad VARCHAR(50), Símbolo VARCHAR(10) );
CREATE TABLE Producto ( ID_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY, Nombre VARCHAR(255), Precio_Neto DECIMAL(10, 2), Código_de_Barras VARCHAR(50), Descripción TEXT, Marca VARCHAR(255), Cantidad INT, Cantidad_minima_aviso INT, Imagen VARCHAR(255),Activo BOOLEAN DEFAULT TRUE , ID_IVA INT, ID_UNIDAD INT, ID_CATEGORIA INT, FOREIGN KEY (ID_IVA) REFERENCES IVA(ID_IVA), FOREIGN KEY (ID_UNIDAD) REFERENCES Medida(ID_UNIDAD), FOREIGN KEY (ID_CATEGORIA) REFERENCES Categoría(ID_CATEGORIA) );
CREATE TABLE Productos_Vendidos (ID_VENTA INT, ID_PRODUCTO INT,Cantidad_de_Venta INT, Precio_de_Venta DECIMAL(10, 2),FOREIGN KEY (ID_VENTA) REFERENCES Venta(ID_VENTA),FOREIGN KEY (ID_PRODUCTO) REFERENCES Producto(ID_PRODUCTO));
CREATE TABLE Proveedor ( ID_PROVEEDOR INT AUTO_INCREMENT PRIMARY KEY, Contacto VARCHAR(255), Razón_Social VARCHAR(255), RUT VARCHAR(20), Activo BOOLEAN DEFAULT TRUE);
CREATE TABLE Compra ( ID_COMPRA INT AUTO_INCREMENT PRIMARY KEY, Precio_Final DECIMAL(10, 2), Fecha_Compra DATE, ID_PROVEEDOR INT, FOREIGN KEY (ID_PROVEEDOR) REFERENCES Proveedor(ID_PROVEEDOR) );
CREATE TABLE Productos_Comprados( ID_COMPRA INT, ID_PRODUCTO INT, Cantidad_de_Compra INT, Precio_de_Compra DECIMAL(10, 2), PRIMARY KEY (ID_COMPRA, ID_PRODUCTO), FOREIGN KEY (ID_COMPRA) REFERENCES Compra(ID_COMPRA), FOREIGN KEY (ID_PRODUCTO) REFERENCES Producto(ID_Producto) );
CREATE TABLE Pago ( ID_PAGO INT AUTO_INCREMENT PRIMARY KEY, Fecha_Pago DATE, Monto DECIMAL(10, 2), ID_PROVEEDOR INT, ID_COMPRA INT, FOREIGN KEY (ID_PROVEEDOR) REFERENCES Proveedor(ID_PROVEEDOR), FOREIGN KEY (ID_COMPRA) REFERENCES Compra(ID_COMPRA) );
CREATE TABLE Usuario(Usuario VARCHAR(40) PRIMARY KEY,Contraseña VARCHAR(50),Nombre VARCHAR(50),Correo VARCHAR(50),Foto_Perfil VARCHAR(255),Fecha_Nacimiento DATE,Precio_por_Tickets DECIMAL(5,2) DEFAULT '200',Color_Fondo VARCHAR(20) DEFAULT "#001F47",Color_Principal VARCHAR(20) DEFAULT "#4DBF38",Color_Secundario VARCHAR(20) DEFAULT "#80D12A");

GRANT ALL PRIVILEGES ON mana.* TO administrador IDENTIFIED BY 'lupf2024';

GRANT SELECT,UPDATE,INSERT,DELETE ON mana.* TO funcionario IDENTIFIED BY "funcionario2024";

GRANT SELECT ON mana.* TO consultor_datos IDENTIFIED BY "consultor2024";

GRANT SELECT, INSERT, UPDATE ON mana.Venta TO contador IDENTIFIED BY "contadordemana"; 
GRANT SELECT, INSERT, UPDATE ON mana.Cobro TO contador;
GRANT SELECT ON mana.Cliente TO contador; 
GRANT SELECT ON mana.Producto TO contador;

GRANT SELECT, INSERT, UPDATE ON mana.Producto TO controlador_stock  IDENTIFIED BY "controlador_stock_mana";

GRANT SELECT, INSERT, UPDATE ON mana.Cliente TO compras_ventas  IDENTIFIED BY "compraventasmana";
GRANT SELECT, INSERT, UPDATE ON mana.Venta TO compras_ventas;
GRANT SELECT, INSERT, UPDATE ON mana.Productos_Vendidos TO compras_ventas;
GRANT SELECT, INSERT, UPDATE ON mana.Cobro TO compras_ventas;
GRANT SELECT, INSERT, UPDATE ON mana.Compra TO compras_ventas;
GRANT SELECT, INSERT, UPDATE ON mana.Productos_Comprados TO compras_ventas;
GRANT SELECT, INSERT, UPDATE ON mana.Pago TO compras_ventas;

