
CREATE DATABASE mana;
USE mana;

CREATE TABLE Sorteo ( ID_SORTEO INT AUTO_INCREMENT PRIMARY KEY, Premio VARCHAR(255), Cantidad INT, Fecha_realización DATE );
CREATE TABLE Cliente ( ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY, Cédula VARCHAR(20), Nombre VARCHAR(255), Deuda DECIMAL(10, 2) DEFAULT '0', Fecha_de_Nacimiento DATE, Tickets_de_Sorteo INT DEFAULT '0', Contacto VARCHAR(255), RUT VARCHAR(20) );
CREATE TABLE Ganador ( ID_CLIENTE INT, ID_SORTEO INT, PRIMARY KEY (ID_CLIENTE, ID_SORTEO), FOREIGN KEY (ID_CLIENTE) REFERENCES Cliente(ID_CLIENTE), FOREIGN KEY (ID_SORTEO) REFERENCES Sorteo(ID_SORTEO) );
CREATE TABLE Venta ( ID_VENTA INT AUTO_INCREMENT PRIMARY KEY, Precio_Final DECIMAL(10, 2), Fecha_Venta DATE, ID_CLIENTE INT, FOREIGN KEY (ID_CLIENTE) REFERENCES Cliente(ID_CLIENTE) );
CREATE TABLE Pago ( ID_PAGO INT AUTO_INCREMENT PRIMARY KEY, Monto DECIMAL(10, 2), Fecha_Pago DATE, ID_CLIENTE INT, ID_VENTA INT, FOREIGN KEY (ID_CLIENTE) REFERENCES Cliente(ID_CLIENTE), FOREIGN KEY (ID_VENTA) REFERENCES Venta(ID_VENTA) );
CREATE TABLE Categoría ( ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY, Título VARCHAR(255), Descripción TEXT );
CREATE TABLE IVA ( ID_IVA INT AUTO_INCREMENT PRIMARY KEY, Tipo VARCHAR(50), Valor DECIMAL(5, 2) );
CREATE TABLE Medida ( ID_UNIDAD INT AUTO_INCREMENT PRIMARY KEY, Unidad VARCHAR(50), Símbolo VARCHAR(10) );
CREATE TABLE Producto ( ID_Producto INT AUTO_INCREMENT PRIMARY KEY, Nombre VARCHAR(255), Precio_Neto DECIMAL(10, 2), Código_de_Barras VARCHAR(50), Descripción TEXT, Marca VARCHAR(255), Cantidad INT, Cantidad_minima_aviso INT, imagen VARCHAR(255), ID_IVA INT, ID_UNIDAD INT, ID_CATEGORIA INT, FOREIGN KEY (ID_IVA) REFERENCES IVA(ID_IVA), FOREIGN KEY (ID_UNIDAD) REFERENCES Medida(ID_UNIDAD), FOREIGN KEY (ID_CATEGORIA) REFERENCES Categoría(ID_CATEGORIA) );
CREATE TABLE Incluye ( ID_Venta INT, ID_Producto INT, Cantidad_de_venta INT, Precio_de_Venta DECIMAL(10, 2), PRIMARY KEY (ID_Venta, ID_Producto), FOREIGN KEY (ID_Venta) REFERENCES Venta(ID_VENTA), FOREIGN KEY (ID_Producto) REFERENCES Producto(ID_Producto) );
CREATE TABLE Proveedor ( ID_PROVEEDOR INT AUTO_INCREMENT PRIMARY KEY, Contacto VARCHAR(255), Razón_Social VARCHAR(255), RUT VARCHAR(20) );
CREATE TABLE Compra ( ID_COMPRA INT AUTO_INCREMENT PRIMARY KEY, Precio_Final DECIMAL(10, 2), Fecha_Compra DATE, ID_PROVEEDOR INT, FOREIGN KEY (ID_PROVEEDOR) REFERENCES Proveedor(ID_PROVEEDOR) );
CREATE TABLE Contiene ( ID_COMPRA INT, ID_PRODUCTO INT, Cantidad_de_Compra INT, Precio_de_Compra DECIMAL(10, 2), PRIMARY KEY (ID_COMPRA, ID_PRODUCTO), FOREIGN KEY (ID_COMPRA) REFERENCES Compra(ID_COMPRA), FOREIGN KEY (ID_PRODUCTO) REFERENCES Producto(ID_Producto) );
CREATE TABLE Cobro ( ID_COBRO INT AUTO_INCREMENT PRIMARY KEY, Fecha_cobro DATE, Monto DECIMAL(10, 2), ID_PROVEEDOR INT, ID_COMPRA INT, FOREIGN KEY (ID_PROVEEDOR) REFERENCES Proveedor(ID_PROVEEDOR), FOREIGN KEY (ID_COMPRA) REFERENCES Compra(ID_COMPRA) );
CREATE TABLE usuario(usuario VARCHAR(40) PRIMARY KEY,contraseña VARCHAR(50),nombre VARCHAR(50),correo VARCHAR(50),fotoperfil VARCHAR(255),fecha_nacimiento DATE);
CREATE TABLE config(precio_x_tickets DECIMAL(5,2));

GRANT ALL PRIVILEGES ON mana.* TO administrador IDENTIFIED BY 'lupf2024';

GRANT SELECT ON mana.* TO funcionario IDENTIFIED BY "funcionario2024";
GRANT INSERT ON mana.* TO funcionario;
GRANT UPDATE ON mana.* TO funcionario;
GRANT DELETE ON mana.* TO funcionario;

GRANT SELECT ON mana.* TO consultor_datos IDENTIFIED BY "consultor2024";

GRANT SELECT, INSERT, UPDATE ON mana.Venta TO contador IDENTIFIED BY "contadordemana"; 
GRANT SELECT, INSERT, UPDATE ON mana.Pago TO contador;
GRANT SELECT ON mana.Cliente TO contador; 
GRANT SELECT ON mana.Producto TO contador;

GRANT SELECT, INSERT, UPDATE ON mana.Producto TO controlador_stock  IDENTIFIED BY "controlador_stockmana";

GRANT SELECT, INSERT, UPDATE ON mana.Cliente TO compras_ventas  IDENTIFIED BY "compraventasmana";
GRANT SELECT, INSERT, UPDATE ON mana.Venta TO compras_ventas;
GRANT SELECT, INSERT, UPDATE ON mana.Incluye TO compras_ventas; GRANT SELECT, INSERT, UPDATE ON mana.Pago TO compras_ventas;
GRANT SELECT, INSERT, UPDATE ON mana.Contiene TO compras_ventas;
GRANT SELECT, INSERT, UPDATE ON mana.Compra TO compras_ventas;
GRANT SELECT, INSERT, UPDATE ON mana.Pago TO compras_ventas;

